//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E2Print.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.TagLinks = new HashSet<TagLink>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<TagLink> TagLinks { get; set; }
    }
}
