//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E2Print.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagLink
    {
        public System.Guid Id { get; set; }
        public System.Guid TagId { get; set; }
        public int ProductId { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
